---
title: "[TIMOB-17086] Android: crashOnLastLaunch always returns true in titanium crittercism module"
---
<table>
<tr><th>Type</th><td>Story</td></tr>
<tr><th>Priority</th><td>Low</td></tr>
<tr><th>Status</th><td>Closed</td></tr>
<tr><th>Resolution</th><td>Not Our Bug</td></tr>
<tr><th>Resolution Date</th><td>2014-06-06T18:04:27.000+0000</td></tr>
<tr><th>Affected Version/s</th><td>Release 3.3.0</td></tr>
<tr><th>Fix Version/s</th><td>n/a</td></tr>
<tr><th>Components</th><td>Android</td></tr>
<tr><th>Labels</th><td>n/a</td></tr>
<tr><th>Reporter</th><td>Allen Yeung</td></tr>
<tr><th>Assignee</th><td>Ingo Muschenetz</td></tr>
<tr><th>Created</th><td>2014-06-06T18:01:40.000+0000</td></tr>
<tr><th>Updated</th><td>2017-03-13T21:31:59.000+0000</td></tr>
</table>

<h3>Description</h3>

The crashOnLastLaunch method always returns true, even after a crash in the app.  The crash displays correctly on the dashboard, but the value always returns true on a subsequent app launch.


<h3>Comments</h3>

<ol>
<li>Allen Yeung 2014-06-06

   Resolving as not our bug since this is an issue with the custom _logCrashException() we use for crittercism.  The API on their side does not correctly hook up the crashOnLastLaunch property with _logCrashException() and they have a task to fix it in a future release.</li>
<li>Lee Morris 2017-03-13

   Closing ticket as this is not our bug.</li>
</ol>


<p><a href="/TIMOB/TIMOB-17086.json">JSON Source</a></p>