---
title: "[TIMOB-4727] KitchenSink: Repeatedly launching Mashups>SOAP test results in logged warnings of messaging a dead thread"
---
<table>
<tr><th>Type</th><td>Bug</td></tr>
<tr><th>Priority</th><td>Trivial</td></tr>
<tr><th>Status</th><td>Closed</td></tr>
<tr><th>Resolution</th><td>Invalid</td></tr>
<tr><th>Resolution Date</th><td>2017-05-02T20:14:15.000+0000</td></tr>
<tr><th>Affected Version/s</th><td>Release 1.7.2</td></tr>
<tr><th>Fix Version/s</th><td>n/a</td></tr>
<tr><th>Components</th><td>Android</td></tr>
<tr><th>Labels</th><td>kitchensink</td></tr>
<tr><th>Reporter</th><td>Eric Merriman </td></tr>
<tr><th>Assignee</th><td>Ingo Muschenetz</td></tr>
<tr><th>Created</th><td>2011-07-19T19:48:43.000+0000</td></tr>
<tr><th>Updated</th><td>2017-05-02T21:02:50.000+0000</td></tr>
</table>

<h3>Description</h3>

Description:
While testing KitchenSink I noticed some new log behavior I hadn't seen in other passes. I was able to find a reproducible case by launching the Mashups>SOAP test, hitting back and launching the test again. By approximately the third attempt, the following will appear in the log:

07-19 11:22:28.157: WARN/MessageQueue(2534): Handler{40acfa10} sending message to a Handler on a dead thread
07-19 11:22:28.157: WARN/MessageQueue(2534): java.lang.RuntimeException: Handler{40acfa10} sending message to a Handler on a dead thread
07-19 11:22:28.157: WARN/MessageQueue(2534):     at android.os.MessageQueue.enqueueMessage(MessageQueue.java:196)
07-19 11:22:28.157: WARN/MessageQueue(2534):     at android.os.Handler.sendMessageAtTime(Handler.java:457)
07-19 11:22:28.157: WARN/MessageQueue(2534):     at android.os.Handler.sendMessageDelayed(Handler.java:430)
07-19 11:22:28.157: WARN/MessageQueue(2534):     at android.os.Handler.post(Handler.java:248)
07-19 11:22:28.157: WARN/MessageQueue(2534):     at org.appcelerator.titanium.kroll.KrollCallback.callAsync(KrollCallback.java:162)
07-19 11:22:28.157: WARN/MessageQueue(2534):     at org.appcelerator.titanium.kroll.KrollCallback.callAsync(KrollCallback.java:96)
07-19 11:22:28.157: WARN/MessageQueue(2534):     at org.appcelerator.titanium.kroll.KrollCallback.callAsync(KrollCallback.java:91)
07-19 11:22:28.157: WARN/MessageQueue(2534):     at ti.modules.titanium.network.TiHTTPClient.fireCallback(TiHTTPClient.java:471)
07-19 11:22:28.157: WARN/MessageQueue(2534):     at ti.modules.titanium.network.TiHTTPClient.fireCallback(TiHTTPClient.java:462)
07-19 11:22:28.157: WARN/MessageQueue(2534):     at ti.modules.titanium.network.TiHTTPClient.setReadyState(TiHTTPClient.java:494)
07-19 11:22:28.157: WARN/MessageQueue(2534):     at ti.modules.titanium.network.TiHTTPClient$ClientRunnable.run(TiHTTPClient.java:1013)
07-19 11:22:28.157: WARN/MessageQueue(2534):     at java.lang.Thread.run(Thread.java:1019)

Steps to Reproduce:
1) Launch KS, built with 1.7.2
2) Ensure you are loggings
3) Navigate to Mashups>SOAP
4) Tap "back"
5) Repeat steps 3 and 4 until you see the log output


Result:
Warnings logged:  java.lang.RuntimeException: Handler{40aa1810} sending message to a Handler on a dead thread

Expected results:
No warnings logged


<h3>Comments</h3>

<ol>
<li>Tony Lukasavage 2011-08-23

   Following near identical steps on the iPhone simulator results in a crash. 
   
   Steps to Reproduce:
   1) Launch KS in iPhone simulator (iOS 4.1), built with 1.7.2
   2) Navigate to Mashups>SOAP
   3) Navigate back to Mashups
   4) Repeat step 2
   
   log output:
   
   [DEBUG] loading: /Users/tlukasavage/Downloads/appcelerator-KitchenSink-284ed4e/Resources/examples/soap.js, resource: Users/tlukasavage/Downloads/appcelerator-KitchenSink-284ed4e/Resources/examples/soap_js
   [DEBUG] include url: file://localhost/Users/tlukasavage/Downloads/appcelerator-KitchenSink-284ed4e/Resources/examples/suds.js
   [DEBUG] loading: /Users/tlukasavage/Downloads/appcelerator-KitchenSink-284ed4e/Resources/examples/suds.js, resource: Users/tlukasavage/Downloads/appcelerator-KitchenSink-284ed4e/Resources/examples/suds_js
   
   Entity: line 1: parser error : Start tag expected, '<' not found
   The service is unavailable.
   ^
   [ERROR] Error Domain=com.google.GDataXML Code=-1 "The operation couldn’t be completed. (com.google.GDataXML error -1.)".   in -[TiDOMDocumentProxy parseString:] (TiDOMDocumentProxy.m:42)
   
   [ERROR] The application has crashed with an unhandled exception. Stack trace:
   0   CoreFoundation                      0x0238c58c __exceptionPreprocess + 156
   1   libobjc.A.dylib                     0x024e0313 objc_exception_throw + 44
   2   appcelerator-KitchenSink-284ed4e    0x000d5d2b -[TiProxy throwException:subreason:location:] + 363
   3   appcelerator-KitchenSink-284ed4e    0x001564a3 -[TiDOMDocumentProxy parseString:] + 451
   4   appcelerator-KitchenSink-284ed4e    0x00162b11 -[XMLModule parseString:] + 737
   5   CoreFoundation                      0x022fcc7d __invoking___ + 29
   6   CoreFoundation                      0x022fcb51 -[NSInvocation invoke] + 145
   7   appcelerator-KitchenSink-284ed4e    0x0004ddf9 -[KrollMethod call:] + 3081
   8   appcelerator-KitchenSink-284ed4e    0x0004c89e KrollCallAsFunction + 542
   9   appcelerator-KitchenSink-284ed4e    0x002d9169 _ZN2TI16TiCallbackObjectINS_8TiObjectEE4callEPNS_10TiExcStateEPS1_NS_7TiValueERKNS_7ArgListE + 391
   10  appcelerator-KitchenSink-284ed4e    0x002b642b cti_op_call_NotTiFunction + 299
   11  ???                                 0x0da0a57e 0x0 + 228631934
   12  appcelerator-KitchenSink-284ed4e    0x00273085 _ZN2TI11Interpreter7executeEPNS_18FunctionExecutableEPNS_10TiExcStateEPNS_10TiFunctionEPNS_8TiObjectERKNS_7ArgListEPNS_14ScopeChainNodeEPNS_7TiValueE + 975
   13  appcelerator-KitchenSink-284ed4e    0x002c485d _ZN2TI10TiFunction4callEPNS_10TiExcStateENS_7TiValueERKNS_7ArgListE + 129
   14  appcelerator-KitchenSink-284ed4e    0x0023bf7b _ZN2TI4callEPNS_10TiExcStateENS_7TiValueENS_8CallTypeERKNS_8CallDataES2_RKNS_7ArgListE + 91
   15  appcelerator-KitchenSink-284ed4e    0x002d7486 TiObjectCallAsFunction + 454
   16  appcelerator-KitchenSink-284ed4e    0x000559f8 -[KrollObject invokeCallbackForKey:withObject:thisObject:] + 856
   17  appcelerator-KitchenSink-284ed4e    0x000452d2 -[ExpandedInvocationOperation main] + 210
   18  Foundation                          0x006a1b76 -[__NSOperationInternal start] + 747
   19  appcelerator-KitchenSink-284ed4e    0x00047c56 -[KrollContext invoke:] + 150
   20  appcelerator-KitchenSink-284ed4e    0x0004685e -[KrollContext main] + 4478
   21  Foundation                          0x0067bcf4 -[NSThread main] + 81
   22  Foundation                          0x0067bc80 __NSThread__main__ + 1387
   23  libsystem_c.dylib                   0x91e89ed9 _pthread_start + 335
   24  libsystem_c.dylib                   0x91e8d6de thread_start + 34
   
   2011-08-23 09:01:05.933 appcelerator-KitchenSink-284ed4e[21080:1a90b] *** Terminating app due to uncaught exception 'org.appcelerator_kitchensink_284ed4e.TiDOMDocumentProxy', reason: 'Error Domain=com.google.GDataXML Code=-1 "The operation couldn’t be completed. (com.google.GDataXML error -1.)".   in -[TiDOMDocumentProxy parseString:] (TiDOMDocumentProxy.m:42)'
   
   *** Call stack at first throw:
   (
   	0   CoreFoundation                      0x0238c5a9 __exceptionPreprocess + 185
   	1   libobjc.A.dylib                     0x024e0313 objc_exception_throw + 44
   	2   appcelerator-KitchenSink-284ed4e    0x000d5d2b -[TiProxy throwException:subreason:location:] + 363
   	3   appcelerator-KitchenSink-284ed4e    0x001564a3 -[TiDOMDocumentProxy parseString:] + 451
   	4   appcelerator-KitchenSink-284ed4e    0x00162b11 -[XMLModule parseString:] + 737
   	5   CoreFoundation                      0x022fcc7d __invoking___ + 29
   	6   CoreFoundation                      0x022fcb51 -[NSInvocation invoke] + 145
   	7   appcelerator-KitchenSink-284ed4e    0x0004ddf9 -[KrollMethod call:] + 3081
   	8   appcelerator-KitchenSink-284ed4e    0x0004c89e KrollCallAsFunction + 542
   	9   appcelerator-KitchenSink-284ed4e    0x002d9169 _ZN2TI16TiCallbackObjectINS_8TiObjectEE4callEPNS_10TiExcStateEPS1_NS_7TiValueERKNS_7ArgListE + 391
   	10  appcelerator-KitchenSink-284ed4e    0x002b642b cti_op_call_NotTiFunction + 299
   	11  ???                                 0x0da0a57e 0x0 + 228631934
   	12  appcelerator-KitchenSink-284ed4e    0x00273085 _ZN2TI11Interpreter7executeEPNS_18FunctionExecutableEPNS_10TiExcStateEPNS_10TiFunctionEPNS_8TiObjectERKNS_7ArgListEPNS_14ScopeChainNodeEPNS_7TiValueE + 975
   	13  appcelerator-KitchenSink-284ed4e    0x002c485d _ZN2TI10TiFunction4callEPNS_10TiExcStateENS_7TiValueERKNS_7ArgListE + 129
   	14  appcelerator-KitchenSink-284ed4e    0x0023bf7b _ZN2TI4callEPNS_10TiExcStateENS_7TiValueENS_8CallTypeERKNS_8CallDataES2_RKNS_7ArgListE + 91
   	15  appcelerator-KitchenSink-284ed4e    0x002d7486 TiObjectCallAsFunction + 454
   	16  appcelerator-KitchenSink-284ed4e    0x000559f8 -[KrollObject invokeCallbackForKey:withObject:thisObject:] + 856
   	17  appcelerator-KitchenSink-284ed4e    0x000452d2 -[ExpandedInvocationOperation main] + 210
   	18  Foundation                          0x006a1b76 -[__NSOperationInternal start] + 747
   	19  appcelerator-KitchenSink-284ed4e    0x00047c56 -[KrollContext invoke:] + 150
   	20  appcelerator-KitchenSink-284ed4e    0x0004685e -[KrollContext main] + 4478
   	21  Foundation                          0x0067bcf4 -[NSThread main] + 81
   	22  Foundation                          0x0067bc80 __NSThread__main__ + 1387
   	23  libsystem_c.dylib                   0x91e89ed9 _pthread_start + 335
   	24  libsystem_c.dylib                   0x91e8d6de thread_start + 34
   )
   
   terminate called throwing an exception</li>
<li>Lee Morris 2017-05-02

   Resolving ticket as Invalid as there is now a new version of Kitchen Sink available and we no longer support the version which relates to this ticket.</li>
</ol>


<p><a href="/TIMOB/TIMOB-4727.json">JSON Source</a></p>