{
	"id": "161204",
	"key": "TIMOB-23571",
	"fields": {
		"issuetype": {
			"id": "1",
			"description": "A problem which impairs or prevents the functions of the product.",
			"name": "Bug",
			"subtask": false
		},
		"project": {
			"id": "10153",
			"key": "TIMOB",
			"name": "Titanium SDK/CLI",
			"projectCategory": {
				"id": "10100",
				"description": "Titanium and related SDKs used in application development",
				"name": "Client"
			}
		},
		"fixVersions": [],
		"resolution": {
			"id": "8",
			"description": "",
			"name": "Needs more info"
		},
		"resolutiondate": "2016-12-27T13:45:11.000+0000",
		"created": "2016-06-20T15:52:09.000+0000",
		"priority": {
			"name": "Critical",
			"id": "1"
		},
		"labels": [
			"android",
			"httpclient",
			"network"
		],
		"versions": [],
		"issuelinks": [],
		"assignee": {
			"name": "emerriman",
			"key": "emerriman",
			"displayName": "Eric Merriman ",
			"active": true,
			"timeZone": "America/Los_Angeles"
		},
		"updated": "2017-06-14T21:21:13.000+0000",
		"status": {
			"description": "The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.",
			"name": "Closed",
			"id": "6",
			"statusCategory": {
				"id": 3,
				"key": "done",
				"colorName": "green",
				"name": "Done"
			}
		},
		"components": [],
		"description": "Hi guys,\r\non android, I'm facing this error:\r\n[ERROR] :  TiHTTPClient: (TiHttpClient-51) [267,267] HTTP Error (java.io.IOException): 404 : Not Found\r\n[ERROR] :  TiHTTPClient: java.io.IOException: 404 : Not Found\r\n[ERROR] :  TiHTTPClient: \tat ti.modules.titanium.network.TiHTTPClient$ClientRunnable.run(TiHTTPClient.java:1227)\r\n[ERROR] :  TiHTTPClient: \tat java.lang.Thread.run(Thread.java:841)\r\n\r\nIt happens when my app starts and logs in to server, download some data. Everything sems to work normally, but in console I have this error. It happens only on android(4.4.4).\r\nThanks",
		"attachment": [],
		"flagged": false,
		"summary": "Android: Strange network error",
		"creator": {
			"name": "max87",
			"key": "max87",
			"displayName": "Marian Kucharcik",
			"active": true,
			"timeZone": "Europe/Prague"
		},
		"subtasks": [],
		"reporter": {
			"name": "max87",
			"key": "max87",
			"displayName": "Marian Kucharcik",
			"active": true,
			"timeZone": "Europe/Prague"
		},
		"environment": "Mac OSX El Capitan\r\nAppc Studio 4.6.0\r\nTi SDK 5.3.0GA",
		"comment": {
			"comments": [
				{
					"id": "389167",
					"author": {
						"name": "sdarda",
						"key": "sdarda",
						"displayName": "Sharif AbuDarda",
						"active": false,
						"timeZone": "Asia/Dhaka"
					},
					"body": "Hello, Can you explain a little more? Does the error causing your app to crash? Please share a sample code that causing the issue in Android. We will test it in our environment.",
					"updateAuthor": {
						"name": "sdarda",
						"key": "sdarda",
						"displayName": "Sharif AbuDarda",
						"active": false,
						"timeZone": "Asia/Dhaka"
					},
					"created": "2016-06-27T20:42:02.000+0000",
					"updated": "2016-06-27T20:42:02.000+0000"
				},
				{
					"id": "389256",
					"author": {
						"name": "max87",
						"key": "max87",
						"displayName": "Marian Kucharcik",
						"active": true,
						"timeZone": "Europe/Prague"
					},
					"body": "Hi Sharif,\r\nthis error is not causing app to crash(as far as I know). The code is very simple - create new xhr request, I'm facing this error in three my apps(two of them use simple xhr with no addition, one is using JSONRPC module(https://github.com/wiistriker/Titanium-JSONRPC-Client) which is simple wrapper, no special code)...\r\nThe error is specific for android only, I test it on Motorola MotoG2, Android 4.4.4\r\nThank you",
					"updateAuthor": {
						"name": "max87",
						"key": "max87",
						"displayName": "Marian Kucharcik",
						"active": true,
						"timeZone": "Europe/Prague"
					},
					"created": "2016-06-28T13:57:54.000+0000",
					"updated": "2016-06-28T13:57:54.000+0000"
				},
				{
					"id": "389337",
					"author": {
						"name": "msamah",
						"key": "msamah",
						"displayName": "Ashraf Abu",
						"active": false,
						"timeZone": "Asia/Singapore"
					},
					"body": "[~max87] Is there a url you can share that would reproduce the issue easily?\r\n\r\nThis seems very specific and hard to reproduce without more information.",
					"updateAuthor": {
						"name": "msamah",
						"key": "msamah",
						"displayName": "Ashraf Abu",
						"active": false,
						"timeZone": "Asia/Singapore"
					},
					"created": "2016-06-29T01:23:35.000+0000",
					"updated": "2016-06-29T01:23:35.000+0000"
				},
				{
					"id": "422010",
					"author": {
						"name": "lmorris",
						"key": "lmorris",
						"displayName": "Lee Morris",
						"active": false,
						"timeZone": "America/Los_Angeles"
					},
					"body": "Echoing the above comments, any further problems please file a new ticket.",
					"updateAuthor": {
						"name": "lmorris",
						"key": "lmorris",
						"displayName": "Lee Morris",
						"active": false,
						"timeZone": "America/Los_Angeles"
					},
					"created": "2017-06-14T21:21:13.000+0000",
					"updated": "2017-06-14T21:21:13.000+0000"
				}
			],
			"maxResults": 6,
			"total": 6,
			"startAt": 0
		}
	}
}