{
	"id": "172624",
	"key": "AC-6023",
	"fields": {
		"issuetype": {
			"id": "1",
			"description": "A problem which impairs or prevents the functions of the product.",
			"name": "Bug",
			"subtask": false
		},
		"project": {
			"id": "12217",
			"key": "AC",
			"name": "Appcelerator - INBOX",
			"projectCategory": {
				"id": "10000",
				"description": "",
				"name": "Customer Service"
			}
		},
		"resolution": {
			"id": "8",
			"description": "",
			"name": "Needs more info"
		},
		"resolutiondate": "2018-12-10T22:41:51.000+0000",
		"created": "2018-11-15T21:49:31.000+0000",
		"labels": [],
		"versions": [],
		"issuelinks": [],
		"assignee": {
			"name": "shossain",
			"key": "shossain",
			"displayName": "Shak Hossain",
			"active": false,
			"timeZone": "America/Los_Angeles"
		},
		"updated": "2018-12-10T22:41:51.000+0000",
		"status": {
			"description": "A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.",
			"name": "Resolved",
			"id": "5",
			"statusCategory": {
				"id": 3,
				"key": "done",
				"colorName": "green",
				"name": "Done"
			}
		},
		"components": [
			{
				"id": "14548",
				"name": "Titanium SDK & CLI",
				"description": "Please enter tickets related to the MobileSDK here."
			}
		],
		"description": "{code:java}\r\nvar canOpenURL = Ti.Platform.openURL(‘test://company/30');\r\n\t\t\t\t\t\t\r\nif (!canOpenURL) {\r\n\r\n}\r\n{code}\r\n\r\n\r\n{code:java}\r\n[ERROR] :  PlatformModule: (main) [83824,99750] Activity not found: test://company/30\r\n[ERROR] :  PlatformModule: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=test://company/30 }\r\n[ERROR] :  PlatformModule: \tat android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1936)\r\n[ERROR] :  PlatformModule: \tat android.app.Instrumentation.execStartActivity(Instrumentation.java:1615)\r\n[ERROR] :  PlatformModule: \tat android.app.Activity.startActivityForResult(Activity.java:4472)\r\n[ERROR] :  PlatformModule: \tat android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)\r\n[ERROR] :  PlatformModule: \tat android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)\r\n[ERROR] :  PlatformModule: \tat android.app.Activity.startActivityForResult(Activity.java:4430)\r\n[ERROR] :  PlatformModule: \tat android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:751)\r\n[ERROR] :  PlatformModule: \tat android.app.Activity.startActivity(Activity.java:4791)\r\n[ERROR] :  PlatformModule: \tat android.app.Activity.startActivity(Activity.java:4759)\r\n[ERROR] :  PlatformModule: \tat ti.modules.titanium.platform.PlatformModule.openURL(PlatformModule.java:214)\r\n[ERROR] :  PlatformModule: \tat org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)\r\n[ERROR] :  PlatformModule: \tat org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:63)\r\n[ERROR] :  PlatformModule: \tat org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:969)\r\n[ERROR] :  PlatformModule: \tat org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1194)\r\n[ERROR] :  PlatformModule: \tat org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:394)\r\n[ERROR] :  PlatformModule: \tat ti.modules.titanium.ui.TableViewRowProxy.handleMessage(TableViewRowProxy.java:215)\r\n[ERROR] :  PlatformModule: \tat android.os.Handler.dispatchMessage(Handler.java:101)\r\n[ERROR] :  PlatformModule: \tat android.os.Looper.loop(Looper.java:164)\r\n[ERROR] :  PlatformModule: \tat android.app.ActivityThread.main(ActivityThread.java:6541)\r\n[ERROR] :  PlatformModule: \tat java.lang.reflect.Method.invoke(Native Method)\r\n[ERROR] :  PlatformModule: \tat com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)\r\n[ERROR] :  PlatformModule: \tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)\r\n[ERROR] :  PlatformModule: (main) [1,99751] Activity not found: test://company/30\r\n[ERROR] :  PlatformModule: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=test://company/30 }\r\n[ERROR] :  PlatformModule: \tat android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1936)\r\n[ERROR] :  PlatformModule: \tat android.app.Instrumentation.execStartActivity(Instrumentation.java:1615)\r\n[ERROR] :  PlatformModule: \tat android.app.Activity.startActivityForResult(Activity.java:4472)\r\n[ERROR] :  PlatformModule: \tat android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)\r\n[ERROR] :  PlatformModule: \tat android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)\r\n[ERROR] :  PlatformModule: \tat android.app.Activity.startActivityForResult(Activity.java:4430)\r\n[ERROR] :  PlatformModule: \tat android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:751)\r\n[ERROR] :  PlatformModule: \tat android.app.Activity.startActivity(Activity.java:4791)\r\n[ERROR] :  PlatformModule: \tat android.app.Activity.startActivity(Activity.java:4759)\r\n[ERROR] :  PlatformModule: \tat ti.modules.titanium.platform.PlatformModule.openURL(PlatformModule.java:214)\r\n[ERROR] :  PlatformModule: \tat org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)\r\n[ERROR] :  PlatformModule: \tat org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:63)\r\n[ERROR] :  PlatformModule: \tat org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:969)\r\n[ERROR] :  PlatformModule: \tat org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1194)\r\n[ERROR] :  PlatformModule: \tat org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:394)\r\n[ERROR] :  PlatformModule: \tat ti.modules.titanium.ui.TableViewRowProxy.handleMessage(TableViewRowProxy.java:215)\r\n[ERROR] :  PlatformModule: \tat android.os.Handler.dispatchMessage(Handler.java:101)\r\n[ERROR] :  PlatformModule: \tat android.os.Looper.loop(Looper.java:164)\r\n[ERROR] :  PlatformModule: \tat android.app.ActivityThread.main(ActivityThread.java:6541)\r\n[ERROR] :  PlatformModule: \tat java.lang.reflect.Method.invoke(Native Method)\r\n[ERROR] :  PlatformModule: \tat com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)\r\n[ERROR] :  PlatformModule: \tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)\r\n[ERROR] :  EGL_emulation: tid 4652: eglSurfaceAttrib(1210): error 0x3009 (EGL_BAD_MATCH)\r\n{code}",
		"attachment": [],
		"flagged": false,
		"summary": "When you try to open a URL that does not exist you get the following error:",
		"creator": {
			"name": "andreas.pingas",
			"key": "andreas.pingas",
			"displayName": "Andreas Pingas",
			"active": true,
			"timeZone": "America/Los_Angeles"
		},
		"subtasks": [],
		"reporter": {
			"name": "andreas.pingas",
			"key": "andreas.pingas",
			"displayName": "Andreas Pingas",
			"active": true,
			"timeZone": "America/Los_Angeles"
		},
		"environment": null,
		"comment": {
			"comments": [
				{
					"id": "443667",
					"author": {
						"name": "sdarda",
						"key": "sdarda",
						"displayName": "Sharif AbuDarda",
						"active": false,
						"timeZone": "Asia/Dhaka"
					},
					"body": "Hello, Can you explain a bit, what you feel the issue here? Also, we need the test platform details. Thanks.",
					"updateAuthor": {
						"name": "sdarda",
						"key": "sdarda",
						"displayName": "Sharif AbuDarda",
						"active": false,
						"timeZone": "Asia/Dhaka"
					},
					"created": "2018-11-16T01:03:28.000+0000",
					"updated": "2018-11-16T01:03:28.000+0000"
				},
				{
					"id": "443985",
					"author": {
						"name": "rmitro",
						"key": "rmitro",
						"displayName": "Rakhi Mitro",
						"active": false,
						"timeZone": "America/Los_Angeles"
					},
					"body": "Hello [~andreas.pingas], \r\nJust passing as followup here. Are you able to get that sorted out?  Please let us know if you need help with this issue.\r\n",
					"updateAuthor": {
						"name": "rmitro",
						"key": "rmitro",
						"displayName": "Rakhi Mitro",
						"active": false,
						"timeZone": "America/Los_Angeles"
					},
					"created": "2018-11-28T09:20:42.000+0000",
					"updated": "2018-11-28T09:20:42.000+0000"
				},
				{
					"id": "444043",
					"author": {
						"name": "andreas.pingas",
						"key": "andreas.pingas",
						"displayName": "Andreas Pingas",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"body": "I have two apps the one app has a button that redirects you and opens the other app. I am using the method below however when the second app is not installed the following error appears. The issue above appears on Android devices. On iOS there is the  Ti.Platform.canOpenURL as a result you dont need the above.",
					"updateAuthor": {
						"name": "andreas.pingas",
						"key": "andreas.pingas",
						"displayName": "Andreas Pingas",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"created": "2018-11-29T08:57:25.000+0000",
					"updated": "2018-11-29T08:57:25.000+0000"
				},
				{
					"id": "444045",
					"author": {
						"name": "rmitro",
						"key": "rmitro",
						"displayName": "Rakhi Mitro",
						"active": false,
						"timeZone": "America/Los_Angeles"
					},
					"body": "[~andreas.pingas],\r\nThanks for your feedback. It would be helpful if you can share a simple test case to reproduce your issues on our end and your environment details.",
					"updateAuthor": {
						"name": "rmitro",
						"key": "rmitro",
						"displayName": "Rakhi Mitro",
						"active": false,
						"timeZone": "America/Los_Angeles"
					},
					"created": "2018-11-29T09:46:59.000+0000",
					"updated": "2018-11-29T09:46:59.000+0000"
				}
			],
			"maxResults": 4,
			"total": 4,
			"startAt": 0
		}
	}
}