{
	"id": "60016",
	"key": "TIMOB-10750",
	"fields": {
		"issuetype": {
			"id": "1",
			"description": "A problem which impairs or prevents the functions of the product.",
			"name": "Bug",
			"subtask": false
		},
		"project": {
			"id": "10153",
			"key": "TIMOB",
			"name": "Titanium SDK/CLI",
			"projectCategory": {
				"id": "10100",
				"description": "Titanium and related SDKs used in application development",
				"name": "Client"
			}
		},
		"fixVersions": [
			{
				"id": "13505",
				"description": "Release 3.0.0",
				"name": "Release 3.0.0",
				"archived": true,
				"released": true,
				"releaseDate": "2012-12-14"
			},
			{
				"id": "14097",
				"description": "Sprint 2012-18 Core",
				"name": "Sprint 2012-18 Core",
				"archived": true,
				"released": true,
				"releaseDate": "2012-09-10"
			}
		],
		"resolution": {
			"id": "1",
			"description": "A fix for this issue is checked into the tree and tested.",
			"name": "Fixed"
		},
		"resolutiondate": "2012-09-06T10:08:56.000+0000",
		"created": "2011-04-15T01:27:46.000+0000",
		"priority": {
			"name": "Medium",
			"id": "3"
		},
		"labels": [
			"bad",
			"developer",
			"ipass1",
			"iphone",
			"path",
			"simulator"
		],
		"versions": [
			{
				"id": "14096",
				"description": "Release 2.1.2",
				"name": "Release 2.1.2",
				"archived": true,
				"released": true,
				"releaseDate": "2012-08-31"
			},
			{
				"id": "13505",
				"description": "Release 3.0.0",
				"name": "Release 3.0.0",
				"archived": true,
				"released": true,
				"releaseDate": "2012-12-14"
			}
		],
		"issuelinks": [],
		"assignee": {
			"name": "mstepanov",
			"key": "mstepanov",
			"displayName": "Max Stepanov",
			"active": true,
			"timeZone": "America/Los_Angeles"
		},
		"updated": "2017-03-21T18:24:46.000+0000",
		"status": {
			"description": "The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.",
			"name": "Closed",
			"id": "6",
			"statusCategory": {
				"id": 3,
				"key": "done",
				"colorName": "green",
				"name": "Done"
			}
		},
		"components": [
			{
				"id": "10206",
				"name": "iOS",
				"description": "iOS Platform"
			}
		],
		"description": "{html}<div><p>Just thought I'd let you know that in Titanium Developer 1.2.2 I\r\nam now getting the following errors when I launch an app in the iOS\r\n4.2 simulator:</p>\r\n<pre>\r\n<code>[INFO] One moment, building ...\r\n[INFO] Detected third-party module: jp.masuidrive.ti.admob/0.1\r\n[INFO] Titanium SDK version: 1.5.1\r\n[INFO] iPhone Device family: iphone\r\n[INFO] iPhone SDK version: 4.2\r\n[ERROR] Error: Traceback (most recent call last):\r\nFile \"/Library/Application Support/Titanium/mobilesdk/osx/1.5.1/iphone/builder.py\", line 1040, in main\r\ncleanup_app_logfiles()\r\nFile \"/Library/Application Support/Titanium/mobilesdk/osx/1.5.1/iphone/builder.py\", line 1038, in cleanup_app_logfiles\r\nos.remove(i)\r\nOSError: [Errno 2] No such file or directory: 'bad path 2F119901-0000-0000-0000-006B00000000'</code>\r\n</pre>\r\n<p>If I click Launch again it works fine. Seems to be that every\r\nother 'launch' works.</p></div>{html}",
		"attachment": [],
		"flagged": false,
		"summary": "iPhone Simulator: bad path crash",
		"creator": {
			"name": "richm",
			"key": "richm",
			"displayName": "richm",
			"active": true,
			"timeZone": "America/Los_Angeles"
		},
		"subtasks": [],
		"reporter": {
			"name": "richm",
			"key": "richm",
			"displayName": "richm",
			"active": true,
			"timeZone": "America/Los_Angeles"
		},
		"environment": null,
		"comment": {
			"comments": [
				{
					"id": "121125",
					"author": {
						"name": "richm",
						"key": "richm",
						"displayName": "richm",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"body": "{html}<div><p>I also get this in 1.6.0 with iOS 4.2 and Developer 1.2.2</p></div>{html}",
					"updateAuthor": {
						"name": "richm",
						"key": "richm",
						"displayName": "richm",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"created": "2011-04-15T01:27:47.000+0000",
					"updated": "2011-04-15T01:27:47.000+0000"
				},
				{
					"id": "217503",
					"author": {
						"name": "mstepanov",
						"key": "mstepanov",
						"displayName": "Max Stepanov",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"body": "http://developer.appcelerator.com/question/131296/crash-every-2nd-time-i-launch",
					"updateAuthor": {
						"name": "mstepanov",
						"key": "mstepanov",
						"displayName": "Max Stepanov",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"created": "2012-09-04T14:15:49.000+0000",
					"updated": "2012-09-04T14:15:49.000+0000"
				},
				{
					"id": "217505",
					"author": {
						"name": "mstepanov",
						"key": "mstepanov",
						"displayName": "Max Stepanov",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"body": "PR pending https://github.com/appcelerator/titanium_mobile/pull/2866",
					"updateAuthor": {
						"name": "mstepanov",
						"key": "mstepanov",
						"displayName": "Max Stepanov",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"created": "2012-09-04T14:17:58.000+0000",
					"updated": "2012-09-04T14:17:58.000+0000"
				},
				{
					"id": "220852",
					"author": {
						"name": "mbelkin",
						"key": "mbelkin",
						"displayName": "Michael Belkin",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"body": "I'm experiencing this with 2.1.3RC",
					"updateAuthor": {
						"name": "mbelkin",
						"key": "mbelkin",
						"displayName": "Michael Belkin",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"created": "2012-09-26T04:37:12.000+0000",
					"updated": "2012-09-26T04:37:12.000+0000"
				},
				{
					"id": "223240",
					"author": {
						"name": "sfeather",
						"key": "sfeather",
						"displayName": "Stephen Feather",
						"active": true,
						"timeZone": "America/New_York"
					},
					"body": "Michael,\r\n\r\nIf you are willing to hack up your iphone/builder.py file the fix is really simple, two back slashes to escape spaces in paths:\r\n\r\nhttps://github.com/appcelerator/titanium_mobile/pull/2866/files",
					"updateAuthor": {
						"name": "sfeather",
						"key": "sfeather",
						"displayName": "Stephen Feather",
						"active": true,
						"timeZone": "America/New_York"
					},
					"created": "2012-10-12T01:16:44.000+0000",
					"updated": "2012-10-12T01:16:44.000+0000"
				},
				{
					"id": "414267",
					"author": {
						"name": "lmorris",
						"key": "lmorris",
						"displayName": "Lee Morris",
						"active": false,
						"timeZone": "America/Los_Angeles"
					},
					"body": "Closing ticket as fixed.",
					"updateAuthor": {
						"name": "lmorris",
						"key": "lmorris",
						"displayName": "Lee Morris",
						"active": false,
						"timeZone": "America/Los_Angeles"
					},
					"created": "2017-03-21T18:24:46.000+0000",
					"updated": "2017-03-21T18:24:46.000+0000"
				}
			],
			"maxResults": 6,
			"total": 6,
			"startAt": 0
		}
	}
}