---
title: "[TIMOB-15654] Anvil: Android run for anvil errors out"
---
<table>
<tr><th>GitHub Issue</th><td>n/a</td></tr>
<tr><th>Type</th><td>Bug</td></tr>
<tr><th>Priority</th><td>High</td></tr>
<tr><th>Status</th><td>Closed</td></tr>
<tr><th>Resolution</th><td>Cannot Reproduce</td></tr>
<tr><th>Resolution Date</th><td>2013-11-07T16:55:04.000+0000</td></tr>
<tr><th>Affected Version/s</th><td>n/a</td></tr>
<tr><th>Fix Version/s</th><td>n/a</td></tr>
<tr><th>Components</th><td>Anvil</td></tr>
<tr><th>Labels</th><td>qe-3.2.0</td></tr>
<tr><th>Reporter</th><td>Lokesh Choudhary</td></tr>
<tr><th>Assignee</th><td>Allen Yeung</td></tr>
<tr><th>Created</th><td>2013-11-04T18:46:47.000+0000</td></tr>
<tr><th>Updated</th><td>2013-11-07T16:55:04.000+0000</td></tr>
</table>

<h3>Description</h3>

<h4>Description:</h4>
1. Try to run any suite for platform android on anvil.

<h4>Actual Result:</h4>
NOTE: I started to see this error after updating the CLI.
1. We get following errors and the run fails:
<code><pre>
LChoudharyMBP:~ lokeshchoudhary$  node /Users/lokeshchoudhary/Desktop/anvil/titanium_mobile_repo/titanium_mobile/anvil/driver/driver.js --platform=android --command="start  --config=default --suite=text/textfield --log-level=verbose"
path.existsSync is now called <code>fs.existsSync</code>.
using Titanium SDK version &lt;3.2.0.v20131025115646&gt;
the custom harness config set at &lt;./anvil/configSet/name.txt&gt; does not contain a name.txt file that provides a harness config set name, ignoring
- waiting for device -
harness uninstalled
harness is not built, building
harness does not exist, creating
temp android harness dir already exist
harness created
harness updated with template
harness suites updated
harness tiapp.xml updated
app.js updated for harness
Traceback (most recent call last):
  File "/Users/lokeshchoudhary/Desktop/anvil/anvilsdk/mobilesdk/osx/3.2.0.v20131025115646/android/builder.py", line 2546, in &lt;module&gt;
    builder = Builder(project_name,sdk_dir,project_dir,template_dir,app_id,is_emulator)
  File "/Users/lokeshchoudhary/Desktop/anvil/anvilsdk/mobilesdk/osx/3.2.0.v20131025115646/android/builder.py", line 458, in __init__
    android_creator.create(parent_dir, project_dir=self.top_dir, build_time=True)
  File "/Users/lokeshchoudhary/Desktop/anvil/anvilsdk/mobilesdk/osx/3.2.0.v20131025115646/android/android.py", line 341, in create
    app_properties = self.app_properties, app_info = self.app_info)
  File "/Users/lokeshchoudhary/Desktop/anvil/anvilsdk/mobilesdk/osx/3.2.0.v20131025115646/android/android.py", line 110, in render
    tmpl = self.load_template(os.path.join(template_dir, 'templates', template_file))
  File "/Users/lokeshchoudhary/Desktop/anvil/anvilsdk/mobilesdk/osx/3.2.0.v20131025115646/android/android.py", line 102, in load_template
    return Template(filename=template, output_encoding='utf-8', encoding_errors='replace')
  File "/Users/lokeshchoudhary/Desktop/anvil/anvilsdk/mobilesdk/osx/3.2.0.v20131025115646/common/mako/template.py", line 93, in __init__
    (code, module) = _compile_text(self, file(filename).read(), filename)
IOError: [Errno 2] No such file or directory: '/Users/lokeshchoudhary/Desktop/anvil/anvilsdk/mobilesdk/osx/3.2.0.v20131025115646/android/templates/AppInfo.java'
error encountered when building harness: 1
</pre></code>

<h4>Expected Result:</h4>
1. We should not get any errors & the anvil run for android should run normally.


<h3>Comments</h3>

<ol>
<li>Lokesh Choudhary 2013-11-04

   I am not able to verify this issue today due to npm issues. But will comment on it soon after the npm issue is fixed.</li>
<li>Lokesh Choudhary 2013-11-04

   Will close if not reproducible after the CLI install issue is fixed. Ticket: TIMOB-15658</li>
<li>Lokesh Choudhary 2013-11-05

   Tried it with latest CLI 3.2.0 & sdk 3.2.0.v20131104164843 & was not reproduce the issue.</li>
<li>Lokesh Choudhary 2013-11-05

   Cannot Reproduce . Closing.</li>
</ol>


<p><a href="/TIMOB/TIMOB-15654.json">JSON Source</a></p>