{
	"id": "166482",
	"key": "TIMOB-24463",
	"fields": {
		"issuetype": {
			"id": "1",
			"description": "A problem which impairs or prevents the functions of the product.",
			"name": "Bug",
			"subtask": false
		},
		"project": {
			"id": "10153",
			"key": "TIMOB",
			"name": "Titanium SDK/CLI",
			"projectCategory": {
				"id": "10100",
				"description": "Titanium and related SDKs used in application development",
				"name": "Client"
			}
		},
		"fixVersions": [],
		"resolution": {
			"id": "6",
			"description": "",
			"name": "Hold"
		},
		"resolutiondate": "2018-03-28T09:52:14.000+0000",
		"created": "2017-03-07T22:50:45.000+0000",
		"priority": {
			"name": "Critical",
			"id": "1"
		},
		"labels": [],
		"versions": [],
		"issuelinks": [],
		"assignee": null,
		"updated": "2019-03-12T01:25:50.000+0000",
		"status": {
			"description": "A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.",
			"name": "Resolved",
			"id": "5",
			"statusCategory": {
				"id": 3,
				"key": "done",
				"colorName": "green",
				"name": "Done"
			}
		},
		"components": [
			{
				"id": "10206",
				"name": "iOS",
				"description": "iOS Platform"
			}
		],
		"description": "Getting a lot of crashes in APM with the following:\r\n\r\nCRASH PLSqliteException: Error occurred calling next on a PLSqliteResultSet. SQLite error: 'disk I/O error' for 'select attempts from last_attempt'",
		"attachment": [],
		"flagged": false,
		"summary": "CRASH PLSqliteException: Error occurred calling next on a PLSqliteResultSet. SQLite error: 'disk I/O error' for 'select attempts from last_attempt'",
		"creator": {
			"name": "perdona",
			"key": "perdona",
			"displayName": "Caio Perdona",
			"active": true,
			"timeZone": "America/Los_Angeles"
		},
		"subtasks": [],
		"reporter": {
			"name": "perdona",
			"key": "perdona",
			"displayName": "Caio Perdona",
			"active": true,
			"timeZone": "America/Los_Angeles"
		},
		"environment": "Ti SDK 5.5.1.GA",
		"closedSprints": [
			{
				"id": 1018,
				"state": "closed",
				"name": "2018 Sprint 07 SDK",
				"startDate": "2018-03-25T21:59:36.637Z",
				"endDate": "2018-04-08T21:59:00.000Z",
				"completeDate": "2018-04-08T17:55:14.467Z",
				"originBoardId": 114
			}
		],
		"comment": {
			"comments": [
				{
					"id": "409673",
					"author": {
						"name": "hknoechel",
						"key": "hansknoechel",
						"displayName": "Hans Knöchel",
						"active": true,
						"timeZone": "Europe/Berlin"
					},
					"body": "Looks like an issue with APSAnalytics. It may or may not be caused by [this line|https://github.com/appcelerator/aps_sdk/blob/master/ios/support/analytics/APSAnalytics/APSAnalytics.m#L181] (private repo) executing the requeueing in a different sync-queue than the one calling it. I saw this a few times in sim-builds, but never took a detailed look into it. As it's really really hard to reproduce, we would either need a reproducible case or try out a new build that uses a different queue. For the second case, you could try to use [this library|https://www.dropbox.com/s/nf4lh1yh0uurtgf/libAPSAnalytics.zip?dl=1] by replacing it in {{~/Library/Application Support/Titanium/mobilesdk/osx/<sdk-version>/iphone/Classes/APSAnalytics}}.",
					"updateAuthor": {
						"name": "hknoechel",
						"key": "hansknoechel",
						"displayName": "Hans Knöchel",
						"active": true,
						"timeZone": "Europe/Berlin"
					},
					"created": "2017-03-07T23:29:30.000+0000",
					"updated": "2017-03-07T23:29:30.000+0000"
				},
				{
					"id": "409788",
					"author": {
						"name": "perdona",
						"key": "perdona",
						"displayName": "Caio Perdona",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"body": "Thanks for the feedback Hans. \r\nWill try that and follow up here...",
					"updateAuthor": {
						"name": "perdona",
						"key": "perdona",
						"displayName": "Caio Perdona",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"created": "2017-03-08T02:57:30.000+0000",
					"updated": "2017-03-08T02:57:30.000+0000"
				},
				{
					"id": "416846",
					"author": {
						"name": "sdarda",
						"key": "sdarda",
						"displayName": "Sharif AbuDarda",
						"active": false,
						"timeZone": "Asia/Dhaka"
					},
					"body": "Hello, Can you follow up on current status of the issue? Thanks.",
					"updateAuthor": {
						"name": "sdarda",
						"key": "sdarda",
						"displayName": "Sharif AbuDarda",
						"active": false,
						"timeZone": "Asia/Dhaka"
					},
					"created": "2017-04-05T15:36:16.000+0000",
					"updated": "2017-04-05T15:37:24.000+0000"
				},
				{
					"id": "423907",
					"author": {
						"name": "hknoechel",
						"key": "hansknoechel",
						"displayName": "Hans Knöchel",
						"active": true,
						"timeZone": "Europe/Berlin"
					},
					"body": "[~perdona] Any update on my feedback? We want to address possible APSAnalytics issues over the next weeks, so any constructive feedback would help.",
					"updateAuthor": {
						"name": "hknoechel",
						"key": "hansknoechel",
						"displayName": "Hans Knöchel",
						"active": true,
						"timeZone": "Europe/Berlin"
					},
					"created": "2017-07-11T15:47:37.000+0000",
					"updated": "2017-07-11T15:47:37.000+0000"
				},
				{
					"id": "436016",
					"author": {
						"name": "hknoechel",
						"key": "hansknoechel",
						"displayName": "Hans Knöchel",
						"active": true,
						"timeZone": "Europe/Berlin"
					},
					"body": "Resolving due to inactivity. As this didn't rise up again, it looks like its not an issue anymore!",
					"updateAuthor": {
						"name": "hknoechel",
						"key": "hansknoechel",
						"displayName": "Hans Knöchel",
						"active": true,
						"timeZone": "Europe/Berlin"
					},
					"created": "2018-03-28T09:52:14.000+0000",
					"updated": "2018-03-28T09:52:14.000+0000"
				},
				{
					"id": "446751",
					"author": {
						"name": "homeinspectorpro",
						"key": "homeinspectorpro",
						"displayName": "Dominic Maricic",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"body": "Was this ever resolved? This error and several variations of it are the top 5 crash causes of our app. We do use the Axway Analytics module as well.",
					"updateAuthor": {
						"name": "homeinspectorpro",
						"key": "homeinspectorpro",
						"displayName": "Dominic Maricic",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"created": "2019-03-12T01:25:50.000+0000",
					"updated": "2019-03-12T01:25:50.000+0000"
				}
			],
			"maxResults": 6,
			"total": 6,
			"startAt": 0
		}
	}
}