{
	"id": "164472",
	"key": "TIMOB-24127",
	"fields": {
		"issuetype": {
			"id": "1",
			"description": "A problem which impairs or prevents the functions of the product.",
			"name": "Bug",
			"subtask": false
		},
		"project": {
			"id": "10153",
			"key": "TIMOB",
			"name": "Titanium SDK/CLI",
			"projectCategory": {
				"id": "10100",
				"description": "Titanium and related SDKs used in application development",
				"name": "Client"
			}
		},
		"fixVersions": [
			{
				"id": "16980",
				"description": "New V8",
				"name": "Release 6.0.0",
				"archived": false,
				"released": true,
				"releaseDate": "2016-11-15"
			}
		],
		"resolution": {
			"id": "1",
			"description": "A fix for this issue is checked into the tree and tested.",
			"name": "Fixed"
		},
		"resolutiondate": "2016-11-11T02:44:26.000+0000",
		"created": "2016-11-10T01:28:19.000+0000",
		"priority": {
			"name": "Critical",
			"id": "1"
		},
		"labels": [
			"qe-6.0.0",
			"regression"
		],
		"versions": [
			{
				"id": "16980",
				"description": "New V8",
				"name": "Release 6.0.0",
				"archived": false,
				"released": true,
				"releaseDate": "2016-11-15"
			}
		],
		"issuelinks": [],
		"assignee": {
			"name": "gmathews",
			"key": "gmathews",
			"displayName": "Gary Mathews",
			"active": true,
			"timeZone": "America/Los_Angeles"
		},
		"updated": "2016-11-11T19:07:56.000+0000",
		"status": {
			"description": "The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.",
			"name": "Closed",
			"id": "6",
			"statusCategory": {
				"id": 3,
				"key": "done",
				"colorName": "green",
				"name": "Done"
			}
		},
		"components": [
			{
				"id": "10202",
				"name": "Android",
				"description": "Android Platform"
			}
		],
		"description": "*This is a regression. This issue is not seen in map module ver.3.0.0.*\r\n\r\nh5.Steps to reproduce:\r\n1. Setup your app to run android maps.\r\n2. Use the code below in your app.js:\r\n{code}\r\nvar MapModule = require('ti.map');\r\n\r\nvar win = Ti.UI.createWindow({\r\n\tbackgroundColor:'white'\r\n});\r\n\r\nvar view = Ti.UI.createView({\r\n\theight:'80%',\r\n\twidth:'80%',\r\n\t// backgroundColor:'red'\r\n});\r\n\r\nvar appc = MapModule.createAnnotation({\r\n    latitude: 37.389569,\r\n    longitude: -122.050212,\r\n    title: 'Appcelerator HQ',\r\n    subtitle: 'Mountain View, CA',\r\n    pincolor: MapModule.ANNOTATION_GREEN\r\n});\r\n\r\nvar mapview = MapModule.createView({\r\n\tmapType: MapModule.NORMAL_TYPE,\r\n    region: {latitude: 37.389569, longitude: -122.050212, latitudeDelta: 0.2, longitudeDelta: 0.2},\r\n    annotations: [appc],\r\n    // width:'50%',\r\n    // height:'50%',\r\n    //backgroundColor:'red'\r\n});\r\n\r\nview.add(mapview);\r\nwin.add(view);\r\nwin.open();\r\n{code}\r\n2. Build for android device.\r\n\r\nh5.Actual results:\r\n1. App crashes after launch with error:\r\n{code}\r\n[ERROR] :  TiApplication: (main) [141,141] Sending event: exception on thread: main msg:java.lang.RuntimeException: Unable to start activity ComponentInfo{com.appcelerator.mapmod/org.appcelerator.titanium.TiActivity}: java.lang.IllegalStateException: The meta-data tag in your app's AndroidManifest.xml does not have the right value.  Expected 9683000 but found 9452000.  You must have the following declaration within the <application> element:     <meta-data android:name=\"com.google.android.gms.version\" android:value=\"@integer/google_play_services_version\" />; Titanium 6.0.0,2016/11/09 07:54,undefined\r\n[ERROR] :  TiApplication: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.appcelerator.mapmod/org.appcelerator.titanium.TiActivity}: java.lang.IllegalStateException: The meta-data tag in your app's AndroidManifest.xml does not have the right value.  Expected 9683000 but found 9452000.  You must have the following declaration within the <application> element:     <meta-data android:name=\"com.google.android.gms.version\" android:value=\"@integer/google_play_services_version\" />\r\n[ERROR] :  TiApplication: \tat android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)\r\n[ERROR] :  TiApplication: \tat android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)\r\n[ERROR] :  TiApplication: \tat android.app.ActivityThread.-wrap12(ActivityThread.java)\r\n[ERROR] :  TiApplication: \tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)\r\n[ERROR] :  TiApplication: \tat android.os.Handler.dispatchMessage(Handler.java:102)\r\n[ERROR] :  TiApplication: \tat android.os.Looper.loop(Looper.java:154)\r\n[ERROR] :  TiApplication: \tat android.app.ActivityThread.main(ActivityThread.java:6119)\r\n[ERROR] :  TiApplication: \tat java.lang.reflect.Method.invoke(Native Method)\r\n[ERROR] :  TiApplication: \tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)\r\n[ERROR] :  TiApplication: \tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)\r\n[ERROR] :  TiApplication: Caused by: java.lang.IllegalStateException: The meta-data tag in your app's AndroidManifest.xml does not have the right value.  Expected 9683000 but found 9452000.  You must have the following declaration within the <application> element:     <meta-data android:name=\"com.google.android.gms.version\" android:value=\"@integer/google_play_services_version\" />\r\n[ERROR] :  TiApplication: \tat com.google.android.gms.common.zze.zzbt(Unknown Source)\r\n[ERROR] :  TiApplication: \tat com.google.android.gms.common.zze.isGooglePlayServicesAvailable(Unknown Source)\r\n[ERROR] :  TiApplication: \tat com.google.android.gms.common.GooglePlayServicesUtil.isGooglePlayServicesAvailable(Unknown Source)\r\n[ERROR] :  TiApplication: \tat com.google.android.gms.maps.internal.zzai.zzdq(Unknown Source)\r\n[ERROR] :  TiApplication: \tat com.google.android.gms.maps.internal.zzai.zzdp(Unknown Source)\r\n[ERROR] :  TiApplication: \tat com.google.android.gms.maps.MapsInitializer.initialize(Unknown Source)\r\n[ERROR] :  TiApplication: \tat com.google.android.gms.maps.SupportMapFragment$zzb.zzbru(Unknown Source)\r\n[ERROR] :  TiApplication: \tat com.google.android.gms.maps.SupportMapFragment$zzb.zza(Unknown Source)\r\n[ERROR] :  TiApplication: \tat com.google.android.gms.dynamic.zza.zza(Unknown Source)\r\n[ERROR] :  TiApplication: \tat com.google.android.gms.dynamic.zza.onCreate(Unknown Source)\r\n[ERROR] :  TiApplication: \tat com.google.android.gms.maps.SupportMapFragment.onCreate(Unknown Source)\r\n[ERROR] :  TiApplication: \tat android.support.v4.app.Fragment.performCreate(Fragment.java:1939)\r\n[ERROR] :  TiApplication: \tat android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1029)\r\n[ERROR] :  TiApplication: \tat android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)\r\n[ERROR] :  TiApplication: \tat android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)\r\n[ERROR] :  TiApplication: \tat android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)\r\n[ERROR] :  TiApplication: \tat android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)\r\n[ERROR] :  TiApplication: \tat android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:547)\r\n[ERROR] :  TiApplication: \tat org.appcelerator.titanium.TiBaseActivity.onStart(TiBaseActivity.java:1341)\r\n[ERROR] :  TiApplication: \tat android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)\r\n[ERROR] :  TiApplication: \tat android.app.Activity.performStart(Activity.java:6696)\r\n[ERROR] :  TiApplication: \tat android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2628)\r\n[ERROR] :  TiApplication: \t... 9 more\r\n{code}\r\n\r\nh5.Expected results:\r\n1. App should build & run successfully.",
		"attachment": [],
		"flagged": false,
		"summary": "Android: Expected 9683000 but found 9452000 error when using map module 3.0.1",
		"creator": {
			"name": "lchoudhary",
			"key": "lchoudhary",
			"displayName": "Lokesh Choudhary",
			"active": true,
			"timeZone": "America/Los_Angeles"
		},
		"subtasks": [],
		"reporter": {
			"name": "lchoudhary",
			"key": "lchoudhary",
			"displayName": "Lokesh Choudhary",
			"active": true,
			"timeZone": "America/Los_Angeles"
		},
		"environment": "Appc Studio : 4.8.0.201611020954\r\nSDK Version : 6.0.0.v20161109075403\r\nMac OS Version : 10.11.6\r\nXcode Version : Xcode 8.1 Build version 8B62\r\nAppc CLI AND Appc NPM : {\"NPM\":\"4.2.8-9\",\"CLI\":\"6.0.0-69\"}\r\nTi CLI : 5.0.10\r\nAlloy : 1.9.4\r\nNode : v4.6.0\r\nMap module : 3.0.1",
		"closedSprints": [
			{
				"id": 752,
				"state": "closed",
				"name": "2016 Sprint 23 SDK",
				"startDate": "2016-11-05T00:39:37.027Z",
				"endDate": "2016-11-19T01:39:00.000Z",
				"completeDate": "2016-11-29T06:51:57.887Z",
				"originBoardId": 114
			}
		],
		"comment": {
			"comments": [
				{
					"id": "400715",
					"author": {
						"name": "gmathews",
						"key": "gmathews",
						"displayName": "Gary Mathews",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"body": "master: https://github.com/appcelerator/titanium_mobile/pull/8594\r\n6_0_X: https://github.com/appcelerator/titanium_mobile/pull/8595",
					"updateAuthor": {
						"name": "gmathews",
						"key": "gmathews",
						"displayName": "Gary Mathews",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"created": "2016-11-10T16:03:47.000+0000",
					"updated": "2016-11-10T16:03:47.000+0000"
				},
				{
					"id": "400817",
					"author": {
						"name": "lchoudhary",
						"key": "lchoudhary",
						"displayName": "Lokesh Choudhary",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"body": "Verified the fix.\r\n\r\nNo error seen when building with map module 3.0.1.\r\nClosing.\r\n\r\nAppc Studio : 4.8.0.201611020954\r\nSDK Version : 6.0.0.v20161111062138\r\nMac OS Version : 10.11.6\r\nXcode Version : Xcode 8.1 Build version 8B62\r\nAppc CLI AND Appc NPM : {\"NPM\":\"4.2.8-9\",\"CLI\":\"6.0.0-69\"}\r\nTi CLI : 5.0.10\r\nAlloy : 1.9.4\r\nNode : v4.6.0",
					"updateAuthor": {
						"name": "lchoudhary",
						"key": "lchoudhary",
						"displayName": "Lokesh Choudhary",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"created": "2016-11-11T19:07:48.000+0000",
					"updated": "2016-11-11T19:07:48.000+0000"
				}
			],
			"maxResults": 2,
			"total": 2,
			"startAt": 0
		}
	}
}