---
title: "[ALOY-952] Non numeric primary key not escaped during query"
---
<table>
<tr><th>Type</th><td>Bug</td></tr>
<tr><th>Priority</th><td>Low</td></tr>
<tr><th>Status</th><td>Resolved</td></tr>
<tr><th>Resolution</th><td>Cannot Reproduce</td></tr>
<tr><th>Resolution Date</th><td>2014-08-19T13:19:50.000+0000</td></tr>
<tr><th>Affected Version/s</th><td>Alloy 1.3.0</td></tr>
<tr><th>Fix Version/s</th><td>n/a</td></tr>
<tr><th>Components</th><td>Models</td></tr>
<tr><th>Labels</th><td>alloy</td></tr>
<tr><th>Reporter</th><td>wahyudinata setiawan</td></tr>
<tr><th>Assignee</th><td>Feon Sua Xin Miao</td></tr>
<tr><th>Created</th><td>2014-02-07T00:21:45.000+0000</td></tr>
<tr><th>Updated</th><td>2014-08-19T13:19:50.000+0000</td></tr>
</table>

<h3>Description</h3>

I am having a weird issue with alloy model generating an unescaped query, even though it uses prepared statement.
To recreate it: 

1. Create a model with a non integer primary key. 
2. Do a simple model.fetch({id: "your_text_id"});


It will generate a query like so: SELECT * FROM table_name WHERE some_primary_key = your_text_id
where you would expect something like the following: SELECT * FROM table_name WHERE some_primary_key = 'your_text_id'

quoted from: <a href="http://developer.appcelerator.com/question/162301/weird-sqlite-escaping-issue" rel="nofollow" target="_blank">http://developer.appcelerator.com/question/162301/weird-sqlite-escaping-issue</a>

<h3>Attachments</h3>

<table>
<thead>
<tr><th>File</th><th>Date</th><th>Size</th></tr><thead>
<tbody>
<tr><td><a href="https://jira-attachments.titaniumsdk.com/ALOY/ALOY-952_50268/aloy-952-test.zip">aloy-952-test.zip</td></td><td>2014-08-06T08:34:11.000+0000</td><td>5907153</td></tr>
</tbody>
<table>

<h3>Comments</h3>

<ol>
<li>Ritu Agrawal 2014-02-07

   Moving this ticket to engineering based on Tony's comment in the Q&A thread included in this ticket.</li>
<li>Feon Sua Xin Miao 2014-08-06

   Tested using attached sample app on Alloy 1.3.0 and 1.4.1. 
   Can't reproduce the issue on v1.4.1.
   
   <code><pre>
   	config: {
   		columns: {
   		    "name": "TEXT",
   		    "countryId": "TEXT PRIMARY KEY"
   		},
   		adapter: {
   			type: "sql",
   			collection_name: "countries",
   			idAttribute: "countryId"
   		}
   	},
   </pre></code>
   
   <code><pre>
   model.fetch({id:'SIN'});
   </pre></code></li>
<li>Tim Poulsen 2014-08-19

   Marking as failed because there doesn't seem to be a way to cancel a review.</li>
<li>Tim Poulsen 2014-08-19

   We are not able to reproduce the issue. Perhaps an intervening change since 1.3.0 has resolved this issue. Please comment here if this remains an issue for you. If you do so, please make sure there's a sample app attached that demonstrates the problem.</li>
</ol>


<p><a href="/ALOY/ALOY-952.json">JSON Source</a></p>