---
title: "[TIMOB-6660] iOS: Drillbit build failure in f093021"
---
<table>
<tr><th>GitHub Issue</th><td>n/a</td></tr>
<tr><th>Type</th><td>Bug</td></tr>
<tr><th>Priority</th><td>Critical</td></tr>
<tr><th>Status</th><td>Closed</td></tr>
<tr><th>Resolution</th><td>Fixed</td></tr>
<tr><th>Resolution Date</th><td>2011-12-14T11:03:48.000+0000</td></tr>
<tr><th>Affected Version/s</th><td>Release 1.8.0.1</td></tr>
<tr><th>Fix Version/s</th><td>Sprint 2011-50, Release 1.8.0.1, Release 2.0.0</td></tr>
<tr><th>Components</th><td>iOS</td></tr>
<tr><th>Labels</th><td>verified-1.8.0.1</td></tr>
<tr><th>Reporter</th><td>Stephen Tramer</td></tr>
<tr><th>Assignee</th><td>Stephen Tramer</td></tr>
<tr><th>Created</th><td>2011-12-14T08:33:43.000+0000</td></tr>
<tr><th>Updated</th><td>2012-01-11T16:20:18.000+0000</td></tr>
</table>

<h3>Description</h3>

We're getting drillbit build failures for iOS in the latest build of 1.8.0.1. The exact error is:

<code><pre>
[ERROR] Error: Traceback (most recent call last):
  File "/Users/stiv/src/appcelerator/titanium_mobile/dist/mobilesdk/osx/1.8.0.1/iphone/builder.py", line 1125, in main
    install_logo(ti, applogo, project_dir, template_dir, app_dir)
  File "/Users/stiv/src/appcelerator/titanium_mobile/dist/mobilesdk/osx/1.8.0.1/iphone/tools.py", line 148, in install_logo
    install_default(applogo, project_dir, template_dir, dest)
  File "/Users/stiv/src/appcelerator/titanium_mobile/dist/mobilesdk/osx/1.8.0.1/iphone/tools.py", line 141, in install_default
    shutil.copy(graphic_path, dest)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/shutil.py", line 88, in copy
    copyfile(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/shutil.py", line 52, in copyfile
    fsrc = open(src, 'rb')
IOError: [Errno 21] Is a directory
</pre></code>

Somehow, this seems to be related to the latest changes with icon handling.

<h3>Comments</h3>

<ol>
<li>Natalie Huynh 2011-12-19

   Fixed: Tested with 
   version=1.8.0.1
   module_apiversion=2
   timestamp=12/19/11 09:47
   githash=22868a1
   Leaving open to verify with 1.9.0</li>
<li>Michael Pettiford 2012-01-11

   Closing this issue as fixed against 1.8.0.1</li>
</ol>


<p><a href="/TIMOB/TIMOB-6660.json">JSON Source</a></p>