---
title: "[AC-3459] SDK 5.2.1 ti.cloudPush 3.4.1 Throws Error on Build on Android 6"
---
<table>
<tr><th>GitHub Issue</th><td>n/a</td></tr>
<tr><th>Type</th><td>Bug</td></tr>
<tr><th>Priority</th><td>n/a</td></tr>
<tr><th>Status</th><td>Closed</td></tr>
<tr><th>Resolution</th><td>Cannot Reproduce</td></tr>
<tr><th>Resolution Date</th><td>2016-04-21T20:43:16.000+0000</td></tr>
<tr><th>Affected Version/s</th><td>n/a</td></tr>
<tr><th>Fix Version/s</th><td>n/a</td></tr>
<tr><th>Components</th><td>Appcelerator Modules</td></tr>
<tr><th>Labels</th><td>android</td></tr>
<tr><th>Reporter</th><td>Haroon Abbasi</td></tr>
<tr><th>Assignee</th><td>Shak Hossain</td></tr>
<tr><th>Created</th><td>2016-04-05T13:20:56.000+0000</td></tr>
<tr><th>Updated</th><td>2016-04-21T20:43:16.000+0000</td></tr>
</table>

<h3>Description</h3>

Running an Android App with Ti SDK 5.2.1 Ti.CloudPush 3.4.1 throws an error when Building the App.

{color:#d04437}ERROR] Application Installer abnormal process termination. Process exit value was 1
[ERROR] :  Failed to run dexer:
[ERROR] :  
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/dynamic/LifecycleDelegate;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/security/ProviderInstaller$1;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/security/ProviderInstaller$ProviderInstallListener;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/security/ProviderInstaller;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/actions/SearchIntents;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/actions/ReserveIntents;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/ErrorDialogFragment;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/GooglePlayServicesUtil;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/Scopes;
[ERROR] :  
[ERROR] :  UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] :  java.lang.RuntimeException: Translation has been interrupted
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:608)
[ERROR] :  	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
[ERROR] :  	at com.android.dx.command.dexer.Main.run(Main.java:277)
[ERROR] :  	at com.android.dx.command.dexer.Main.main(Main.java:245)
[ERROR] :  	at com.android.dx.command.Main.main(Main.java:106)
[ERROR] :  Caused by: java.lang.InterruptedException: Too many errors
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:600)
[ERROR] :  	... 4 more
TRACE  | titanium exited with exit code 1


<h3>Comments</h3>

<ol>
<li>Sharif AbuDarda 2016-04-05

   Hello, 
   
   I tried to reproduce the issue With SDK 5.2.1.GA with ti.cloudpush 3.4.1. I wasn't able to reproduce the issue in Android 4.4.2 device. I would suggest you to use ti.cloudpush 3.4.1 with SDK 5.2.1.GA. If you don't have version 3.4.1 available please run 
   
   $ gittio install ti.cloudpush@3.4.1
   
   Regards,
   Sharif</li>
<li>Haroon Abbasi 2016-04-05

   Please check this issue on android 6
   i just checked on 
   SDK 5.2.2 ti.cloudPush 3.4.1 Throws Error on Build on Android 6</li>
<li>Brad Ball 2016-04-12

   Same as Haroon Abbasi. Updated my previously working app to SDK 5.2.2GA and ti.cloudpush 3.4.1 and I get this error when I try to build for Android 6.</li>
<li>Haroon Abbasi 2016-04-13

   Hi @bradleycorn, appcelerator has issue in regard to duplicate libraries within android modules.
   
   so in Ti.cloudpush has specific play store libraries referenced, if any other module you have in your project also has playstore service libraries within their module then it cause conflict.
   
   in my case it was Google Anlaytics module which also has reference to goole play services within it which cause conflict with Ti.CloudPush module.
   
   so do check you don't have same libraries within two different android modules. if one has it then either you need to make android module build excluding that library or you have to disable one of those module to resolve conflict. </li>
<li>Nazmus Salahin 2016-04-14

   Hello,
   I am not able to reproduce this issue on Android 6. I am able to build app without any error where I am using ti.cloudpush 3.4.1.
   Steps.
   1.  Install ti.cloudpush3.4.1 in SDK loaction.
   2. Create a default classic project for android.
   3. Add the module in tiapp.xml.
   4. Replace the app.js file with the given example app.js in the module.
   5. Build and run the app on Android 6. >> No error is produced while building and the app runs.
   
   When the app runs "Failed to register" alert is shown which is obvious. Thing that is in consideration here is the app builds and runs on Android 6 without any error.
   
   [Screenshot](<a href="http://s21.postimg.org/4q6vgallz/image.png)" rel="nofollow" target="_blank">http://s21.postimg.org/4q6vgallz/image.png)</a>
   
   
   *Environment*:
   
   *Device info:* Nexus7 (android 6.0.1)
   *Node.js Version:* 0.12.7
   *npm Version:* 2.11.3
   *Titanium SDKs:* 5.2.2.GA and 5.2.1.GA
   *Java Development Kit Version:* 1.8.0_73
   *Titanium CLI Version:*  5.0.5
   *Appcelerator CLI Version:*  5.2.2
   *Appcelerator Studio:* 4.4.0.201511241829</li>
</ol>


<p><a href="/AC/AC-3459.json">JSON Source</a></p>